code --install-extension abusaidm.html-snippets
code --install-extension austin.vscode-twitter
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension cymonk.sql-formatter
code --install-extension EditorConfig.EditorConfig
code --install-extension eiminsasete.apacheconf-snippets
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension GrapeCity.gc-excelviewer
code --install-extension HvyIndustries.crane
code --install-extension ikappas.phpcs
code --install-extension imperez.smarty
code --install-extension jakebathman.mysql-syntax
code --install-extension jebbs.plantuml
code --install-extension joe-re.sql-language-server
code --install-extension junstyle.php-cs-fixer
code --install-extension mikeburgh.xml-format
code --install-extension mikestead.dotenv
code --install-extension mosapride.zenkaku
code --install-extension mrmlnc.vscode-apache
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mtxr.sqltools
code --install-extension onecentlin.laravel-blade
code --install-extension onecentlin.laravel-extension-pack
code --install-extension onecentlin.laravel5-snippets
code --install-extension pizzacat83.codic
code --install-extension qinjia.view-in-browser
code --install-extension redhat.java
code --install-extension ryannaddy.laravel-artisan
code --install-extension sachittandukar.laravel-5-snippets
code --install-extension slevesque.vscode-autohotkey
code --install-extension small.php-ci
code --install-extension tomoki1207.pdf
code --install-extension Tyriar.sort-lines
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-maven
code --install-extension yzane.markdown-pdf
